// app.js

App({
  onLaunch() {
    console.log('Ap has launched')
    wx.loadFontFace({
      family: 'MyCustomFont',
      global: true,
      source: 'url("/fonts/Marcellus-Regular.woff")',
      complete(response) {
        console.log("load")
      }
    })
  },
  globalData: {
    userInfo: null,
    language: 'en',
    navBarHeight: wx.getMenuButtonBoundingClientRect().height+ 9 + wx.getSystemInfoSync().statusBarHeight,
    userInfo: null,
    tabPages: ["pages/profile/profile","pages/favourite/favourite","pages/homepage/homepage"],
    calorieGrace: 1.1,
    popUp:false,
    firstLoad: true,
    headLine: [
      {title: "German Charity Bazaar Handover of 2022`s Donation at the German Embassy in Beijing", date: "17.March 2023", body: "For almost 30 years, the German Charity Christmas Bazaar has traditionally taken place on the first Advent on the grounds of the German Embassy in Beijing. There, people from a wide variety of nations and cultures have the opportunity to get in the mood for Christmas with German delicacies and buying handmade gifts. The proceeds are used to support aid projects in and around Beijing. These projects take care of children, parents and families, sick and disadvantaged people and people with disabilities.Unfortunately, in 2022 the bazaar had to be canceled for the third time in a row due to Covid. Despite this, the participating charities managed to raise over RMB 200,000 in donations.The handover event was under the patronage of the German Ambassador Dr. Patricia Flor, who is very happy that the German Charity Christmas Bazaar can finally take place again this year. With longer opening hours and even more Christmas Flair than ever before!", url: "http://charitybasar.cn/wp-content/uploads/2023/09/2303-Spendeübergabe-1.jpg"},
      {title: "Advent wreath in summer?", date: "28.September 2022", body: "In a quarter of a year it will be Christmas. Isn’t that time enough to take care of can  dles, wreath and other Christmas decorations? Not for the Christmas angels! They already have to be busy, because it’s not that long until the Christmas bazaar on December 2, 2023, when many more Advent wreaths are to be put up and decorated, gnomes and Christmas trees are to be sewn, and many other beautiful things are to be created. The Christmas angels have their hands full. Because the hut of the Christmas angels on the Christmas market should and will again this year offer a rich selection of different, beautiful Christmas decorations.", url: "http://charitybasar.cn/wp-content/uploads/2022/09/IMG_4281.jpg"},
      {title: "A success story", date: "3.September 2022", body: "The German Christmas Bazaar has long supported Hong Dandan, an institution that helps blind and visually impaired people. Liu Xinming is a girl who was supported by Hong Dandan. Through Hong Dandan’s cinema project, Liu Xinming learned that blind people can also paint. With the support of her parents and volunteers, she has learned to associate colors with emotions. She puts paint directly on canvas with her fingers – and with success. In August, her first solo exhibition", url: "http://charitybasar.cn/wp-content/uploads/2023/10/IMG_4492-e1698594377535.jpeg"},
      {title: "The German Christmas Bazaar is looking for you!", date: "8.May 2022", body: " THE CHRISTMAS BAZAAR LIVES……FROM PARTICIPATION! The organisation team of the German Charity Christmas Bazaar is still looking for support for this year’s bazaar on 2 December. This is urgently needed to ensure the organisation and running of the bazaar and to raise money for the Charities. 100% of the proceeds will be donated.If you can imagine spending at least two hours of your time on the day of the bazaar in a pre-Christmas atmosphere for a good cause, we look forward to hearing from you. In particular, we are looking for support for the following activities:  – Admission control of the applicable admission conditions – Ticket sales and advertising for the raffle– at the fundraising campaign ‘Christmas with Heart`– in the coffee and cake house team in setting up and dismantling as well as selling – in the biscuits & jams team in setting up and dismantling as well as selling – in the Christmas Angels team in setting up and dismantling as well as selling – Photographer or accompaniment of the photographer at the photo tent – Father Christmas in Santa costume – Coordination/organisation of deliveries and set-up and dismantling outside bazaar hours Perhaps you would prefer to bake a cake or biscuits? Of course, you can also help in more than one area.For more information and answers to your questions, send an email to contact@charitybasar.cn We look forward to seeing you! Your team of the German Charity Christmas Bazaar ", url: "http://charitybasar.cn/wp-content/uploads/2022/05/basar-12.jpg"},
      {title: "Review of the Christmas Bazaar 2018", date: "8.May 2022", body: "As every year, the Christmas Bazaar took place at the end of November on the last weekend before the 1st. Advent on the premises of the German Embassy. The rush of visitors ensured a lot of income, so that a high amount of donations could be handed over to the aid organizations. ", url: "http://charitybasar.cn/wp-content/uploads/2022/06/basar2019-31.jpg"},
    ],
    charities: [
      {name: "Beijing Huiling", title:"Residential groups and workshops for mentally handicapped people", body: "Beijing Huiling provides innovative services for young people and adults with learning disabilities and their families. Its goal is to empower people with disabilities and inform the public in China. Every year around 5200 visitors are looked after by Beijing Huiling.", url: "http://charitybasar.cn/wp-content/uploads/2023/11/2023Huiling_Background.png", video: "http://charitybasar.cn/wp-content/uploads/2023/11/2023Huiling-Video.mp4", web:"http://en.bj.hlcn.org/"},
      {name: "Bethel", title:"Home for visually impaired children with all-day care", body: "Bethel was founded in 2003 by Guillaume and Delphine Gauvain, who recognized that care for blind children in orphanages in China was lacking. Bethel's mission is to provide visually impaired orphans of all ages with a safe, loving and stimulating environment to grow, laugh and experience all that life has to offer. Bethel opened its first foster home and school in 2003 with just 3 children. Over the last 15 years, we have carried out more than 138 adoptions and cared for and raised 328 orphans in our centers. We know that a family structure is essential for the healthy development of children. That's why we strive to create a family unit in our centers by providing each child with a small group of nannies and teachers who act as constant caregivers. In this way, we can create a basis of trust and continually work to ensure that our children develop well.", url: "http://charitybasar.cn/wp-content/uploads/2023/11/2023Bethel_Background.png", video: "http://charitybasar.cn/wp-content/uploads/2023/11/2023BETHEL-Video.mp4", web: "https://www.bethelchina.org/"},
      {name: "Hope", title:"Therapeutic riding for people with disabilities", body: "HOPE is a recognized non-governmental organization that has been providing equine-assisted activities and therapies (EAAT) for people with disabilities since 2009. Over the past 14 years, the organization has supported more than 780 participants and empowered them to lead independent lives.", url: "http://charitybasar.cn/wp-content/uploads/2023/11/2023Hope_Background.png", video: "http://charitybasar.cn/wp-content/uploads/2023/11/HOPE-Video-30秒.mp4", web: "https://www.hopebeijing.org/"},
      {name: "Love & Hope", title:"Vocational school for disadvantaged young people from ethnic minorities", body: "Love & Hope (Beijing) Center for Migrant is a recognized, registered organization committed to the education of less privileged, poor migrant children and women from rural areas. The center has set up a fund to help these children through free, in-service training and educational programs. Love & Hope also focuses on the education and training (including to become dental technicians) of women from rural areas. Love & Hope believes that empowerment through knowledge can transform the lives of these children, and that educating an underprivileged woman can have an impact that resonates for generations.", url: "http://charitybasar.cn/wp-content/uploads/2023/11/2023LoveHope_Background.png", video: "http://charitybasar.cn/wp-content/uploads/2023/11/2023Love-and-Hope-Video.mp4", web: "http://en.bj.hlcn.org/"},
      {name: "JIMIN QIZHI Rehabiliation center", title:"Special school and boarding school for mentally handicapped children and young people", body: "The children receive support and are empowered to use their opportunities to participate in society and to develop independent perspectives in life.", url: "http://charitybasar.cn/wp-content/uploads/2023/11/2023Qizhi_Background-1.png", video: "http://charitybasar.cn/wp-content/uploads/2023/11/2023Qizhi-Video.mp4", web:"http://www.bjqz.net/"},
      {name: "Rainbow foundation", title:"Help for children with cancer and their relatives", body: "The Rainbow Foundation is committed to helping children and families with malignant tumors, bringing practical care and help into their treatment lives. The enormous impact of malignant tumors on each patient and his family is unimaginable, and throughout the entire treatment period, the patient's body and psyche are also unimaginable. We therefore hope to be able to accompany patients and families together through this difficult time.", url: "http://charitybasar.cn/wp-content/uploads/2023/11/2023Rainbow_Background-1.png", video: "http://charitybasar.cn/wp-content/uploads/2023/11/2023Rainbow-Video.mp4", web: "http://www.rainbowi.cn%20"},
      {name: "Stars and Rain", title:"Training center for parents and teachers of autistic children", body: "Founded in 1993 by a parent, it is the first non-governmental educational organization in China to care for children with autism. With their unique parenting courses, Stars and Rains has helped more than 20,000 families with autistic children over the past 30 years, giving parents the skills to raise their children. Stars and Rain also operates a group home for several teenagers with autism and related disabilities. Currently, the organization is facing some financial challenges and needs to increase pensions in order to survive.", url: "http://charitybasar.cn/wp-content/uploads/2023/11/2023StarsRain_Background.png", web:"http://www.guduzh.org.cn"},
    ]
  },
})